_wandb:
    value:
        cli_version: 0.28.0
        e:
            qcxchdnal2m9v7jjsouoxx2ikr840s7n:
                codePath: train.py
                codePathLocal: train.py
                email: mohamedtine17@gmail.com
                executable: /home/darrius/project/DRL2/.venv/bin/python3
                git:
                    commit: 335c0345fc21608f215dbfd5ee31d2fb5475a9a2
                    remote: git@github.com:mkosemes1/DRL2.git
                host: darrius
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/darrius/project/DRL2/train.py
                python: CPython 3.12.3
                root: /home/darrius/project/DRL2
                startedAt: "2026-07-18T04:02:10.907354Z"
                writerId: qcxchdnal2m9v7jjsouoxx2ikr840s7n
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.28.0
            "12": 0.28.0
            "13": linux-x86_64
clip_eps:
    value: 0.1
ent_coef:
    value: 0.01
epochs:
    value: 488
gae_lambda:
    value: 0.95
gamma:
    value: 0.999
lr:
    value: 3e-05
value_coef:
    value: 0.5
